export const SERVICES = {
  ABOUT: 'ABOUT_SERVICE',
  CHANGELOG: 'CHANGELOG_SERVICE',
  CHEATS: 'CHEATS_SERVICE',
  HOME: 'HOME_SERVICE',
  TRANSLATION: 'TRANSLATION_SERVICE',
  VOICES: 'VOICES_SERVICE'
}

export const REPOSITORIES = {
  ABOUT: 'ABOUT_REPOSITORY',
  CHANGELOG: 'CHANGELOG_REPOSITORY',
  CHEATS: 'CHEATS_REPOSITORY',
  HOME: 'HOME_REPOSITORY',
  TRANSLATION: 'TRANSLATION_REPOSITORY',
  VOICES: 'VOICES_REPOSITORY'
}
